name: "Update Template Flake Locks"

on:
  workflow_dispatch: # Allow manual trigger
  schedule:
    - cron: '0 15 * * 5' # Run every Saturday at 00:00 JST (Friday 15:00 UTC)

jobs:
  list-templates:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    outputs:
      templates: ${{ steps.set-templates.outputs.templates }}
    steps:
      - uses: actions/checkout@v6

      - uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GH_TOKEN }}

      - name: List templates
        id: set-templates
        uses: ./.github/actions/list-templates

  update-template-flake-lock:
    needs: list-templates
    permissions:
      contents: write
      pull-requests: write
    strategy:
      matrix:
        template: ${{ fromJSON(needs.list-templates.outputs.templates) }}
        exclude:
          - template: haskell
      fail-fast: false # Continue even if one template fails
    uses: gawakawa/.github/.github/workflows/update-flake-lock.yml@main
    with:
      auto-merge: true
      path-to-flake-dir: templates/${{ matrix.template }}
      pr-title: "[${{ matrix.template }}] ⬆️ Update flake.lock"
      branch: update-flake-lock/${{ matrix.template }}
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}

  update-haskell-flake-lock:
    needs: list-templates
    if: contains(fromJSON(needs.list-templates.outputs.templates), 'haskell')
    permissions:
      contents: write
      pull-requests: write
    uses: ./.github/workflows/update-flake-lock-haskell.yml
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
